version: '3.4'

services:
  myproject.api:
    image: myproject-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=SampleCQRSDbXDB;User=sa;Password=YourPassword.123;TrustServerCertificate=True;
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "YourPassword.123"
      ACCEPT_EULA: "Y"
    ports:
      - "1533:1433"
